// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/trends/service.proto

package trends

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrendsServiceClient is the client API for TrendsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrendsServiceClient interface {
	GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*GetTrendsResponse, error)
}

type trendsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrendsServiceClient(cc grpc.ClientConnInterface) TrendsServiceClient {
	return &trendsServiceClient{cc}
}

func (c *trendsServiceClient) GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*GetTrendsResponse, error) {
	out := new(GetTrendsResponse)
	err := c.cc.Invoke(ctx, "/api.trends.TrendsService/GetTrends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendsServiceServer is the server API for TrendsService service.
// All implementations should embed UnimplementedTrendsServiceServer
// for forward compatibility
type TrendsServiceServer interface {
	GetTrends(context.Context, *GetTrendsRequest) (*GetTrendsResponse, error)
}

// UnimplementedTrendsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTrendsServiceServer struct {
}

func (UnimplementedTrendsServiceServer) GetTrends(context.Context, *GetTrendsRequest) (*GetTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrends not implemented")
}

// UnsafeTrendsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrendsServiceServer will
// result in compilation errors.
type UnsafeTrendsServiceServer interface {
	mustEmbedUnimplementedTrendsServiceServer()
}

func RegisterTrendsServiceServer(s grpc.ServiceRegistrar, srv TrendsServiceServer) {
	s.RegisterService(&TrendsService_ServiceDesc, srv)
}

func _TrendsService_GetTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendsServiceServer).GetTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.trends.TrendsService/GetTrends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendsServiceServer).GetTrends(ctx, req.(*GetTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrendsService_ServiceDesc is the grpc.ServiceDesc for TrendsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrendsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.trends.TrendsService",
	HandlerType: (*TrendsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrends",
			Handler:    _TrendsService_GetTrends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/trends/service.proto",
}
