# From https://docs.docker.com/compose/gettingstarted/
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      REDIS_URL: redis:6379
  redis:
    image: "redis:alpine"