# From https://docs.docker.com/compose/gettingstarted/
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
      REDIS_SERVICE: redis
  redis:
    image: "redis:alpine"