name: e2e
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: read
  contents: read

jobs:
  run_e2e_tests:
    name: e2e tests
    runs-on: ubuntu-20.04
    env:
      GOPRIVATE: namespacelabs.dev/*
      NSL_GH_SERVICE: ${{ secrets.NSL_GH_SERVICE }}
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout foundation
        uses: actions/checkout@v3
        with:
          repository: namespacelabs/foundation
          path: foundation
          token: ${{ secrets.NSL_GH_SERVICE }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Configure Git
        run: git config --global url.https://$NSL_GH_SERVICE@github.com/.insteadOf https://github.com/

      # Required by buildkit gha cache.
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Setup cross-invocation caching (Go)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-fnrun-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-fnrun-

      - name: Build fn
        env:
          CGO_ENABLED: 0
        run: cd ./foundation/ && go install ./cmd/fn

      - name: Prepare development environment
        run: cd ./main/todos && fn prepare

      - name: Print kubectl cluster-info
        run: kubectl cluster-info

      - name: Run all tests
        run: |
          cd ./main/todos && fn test \
            --buildkit_import_cache=type=gha \
            --buildkit_export_cache=type=gha,mode=max \
            --use_prebuilts=true \
            --golang_use_buildkit=false \
            --include_servers

      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                "title": "${{ job.status }}: ${{ github.workflow }}",
                "title_link": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks",
                "text": "${{ github.repository }}@${{ github.ref }}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                "fields": [{ "value": ${{ toJson(github.event.head_commit.message) }}, "short": false }],
                "footer": "${{ github.event.head_commit.committer.name }} at ${{ github.event.head_commit.timestamp }}",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure() && github.event_name == 'push'
